/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceContractSol from "./GovernanceContract.sol";
export type { governanceContractSol };
import type * as governanceStandard from "./Governance_standard";
export type { governanceStandard };
export type { Box } from "./Box";
