/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governanceContractSol from "./GovernanceContract.sol";
export * as tImelockSol from "./TImelock.sol";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
