/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governanceContractSol from "./GovernanceContract.sol";
export * as governanceStandard from "./Governance_standard";
export { Box__factory } from "./Box__factory";
