/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceContractSol from "./GovernanceContract.sol";
export type { governanceContractSol };
import type * as tImelockSol from "./TImelock.sol";
export type { tImelockSol };
export type { GovernanceToken } from "./GovernanceToken";
